const GET_LIST_INFO = 'APP/GET_LIST_INFO';
const SET_LIST_INFO = 'APP/SET_LIST_INFO';
const GET_UPDATE_STATUS_ROW = 'APP/GET_UPDATE_STATUS_ROW';
const SET_UPDATE_STATUS_ROW = 'APP/SET_UPDATE_STATUS_ROW';
const GET_LIST_ADD = 'APP/GET_LIST_ADD';
const SET_LIST_ADD = 'APP/SET_LIST_ADD';
const SET_OPERATION_FLAG = 'APP/SET_OPERATION_FLAG';

export {
    GET_LIST_INFO,
    SET_LIST_INFO,
    GET_UPDATE_STATUS_ROW,
    SET_UPDATE_STATUS_ROW,
    GET_LIST_ADD,
    SET_LIST_ADD,
    SET_OPERATION_FLAG
}